# Production overrides
services:
  server:
    build:
      dockerfile: ../docker/server/Dockerfile.prod
    environment:
      - DJANGO_DEBUG=false
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  client:
    build:
      dockerfile: ../docker/client/Dockerfile.prod
    restart: unless-stopped
    command: >
      sh -c "npm run build &&
             cp -r dist/* /app/dist/"

  caddy:
    restart: unless-stopped
    profiles:
      - '' # Enable by default in prod

  postgres:
    restart: unless-stopped
